Fix error: undefined reference to `_ftrace_mcount'
    [100%] Linking C executable ulpatch_test
    /usr/bin/ld: patch/libulpatch_test_patch.a(patch.c.o): in function `test_Patch_ftrace_object':
    /home/rongtao/Git/ulpatch/src/tests/patch/patch.c:238:(.text+0x698): undefined reference to `_ftrace_mcount'
    collect2: error: ld returned 1 exit status
    make[2]: *** [src/tests/CMakeFiles/ulpatch_test.dir/build.make:462: src/tests/ulpatch_test] Error 1
    make[1]: *** [CMakeFiles/Makefile2:696: src/tests/CMakeFiles/ulpatch_test.dir/all] Error 2
    make: *** [Makefile:136: all] Error 2

Fix: commit ab9fa445577b ("tests: CMakeLists.txt: Support add_subdirectory()")
Signed-off-by: Rong Tao <rongtao@cestc.cn>