task.c: Fix error: ignoring return value of ‘readlink’
    /xxx/xxx/src/utils/task.c: In function ‘open_task’:
    /xxx/xxx/src/utils/task.c:1513:25: error: ignoring return value of ‘readlink’
    declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
     1513 |                         readlink(proc_fd_dir, fd->symlink, PATH_MAX);
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Rong Tao <rongtao@cestc.cn>