Default link zstd
Errors:

[ 38%] Linking C executable ultask
/usr/bin/ld.bfd: /usr/lib64/libbfd.a(compress.o): undefined reference to symbol 'ZSTD_compress'
/usr/bin/ld.bfd: /usr/lib64/libzstd.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/ultask.dir/build.make:119: src/ultask] Error 1
make[1]: *** [CMakeFiles/Makefile2:752: src/CMakeFiles/ultask.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

[ 99%] Generating make-bfd.log
  CC  symbol.c to symbol.o
  LD  symbol
/usr/bin/ld.bfd: /usr/lib64/libbfd.a(compress.o): in function `decompress_contents':
/usr/src/debug/binutils-2.46.1-1.fc44.x86_64/build-x86_64-redhat-linux/bfd/../../bfd/compress.c:533:(.text+0x1cd): undefined reference to `ZSTD_decompress'
/usr/bin/ld.bfd: /usr/src/debug/binutils-2.46.1-1.fc44.x86_64/build-x86_64-redhat-linux/bfd/../../bfd/compress.c:535:(.text+0x1d5): undefined reference to `ZSTD_isError'
/usr/bin/ld.bfd: /usr/lib64/libbfd.a(compress.o): in function `bfd_compress_section_contents':
/usr/src/debug/binutils-2.46.1-1.fc44.x86_64/build-x86_64-redhat-linux/bfd/../../bfd/compress.c:659:(.text+0x12a9): undefined reference to `ZSTD_compress'
/usr/bin/ld.bfd: /usr/src/debug/binutils-2.46.1-1.fc44.x86_64/build-x86_64-redhat-linux/bfd/../../bfd/compress.c:664:(.text+0x12b5): undefined reference to `ZSTD_isError'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:43: symbol] Error 1
make[2]: *** [tests/bfd/CMakeFiles/tests_bfd.dir/build.make:73: tests/bfd/make-bfd.log] Error 2
make[1]: *** [CMakeFiles/Makefile2:1649: tests/bfd/CMakeFiles/tests_bfd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Signed-off-by: Rong Tao <rongtao@cestc.cn>