aarch64/regs.h: Fix error: ‘struct user_regs_struct’ has no member named ‘syscall_regs’
[ 14%] Building C object src/utils/CMakeFiles/ulpatch_utils.dir/task-syscall.c.o
In file included from /home/rongtao/Git/ulpatch/src/utils/task-syscall.c:25:
/home/rongtao/Git/ulpatch/src/utils/task-syscall.c: In function ‘task_syscall’:
/home/rongtao/Git/ulpatch/src/utils/../arch/aarch64/regs.h:10:21: error: ‘struct user_regs_struct’ has no member named ‘syscall_regs’
   10 |                 regs.regs[8] = (unsigned long)nr;       \
      |                     ^
/home/rongtao/Git/ulpatch/src/utils/task-syscall.c:147:9: note: in expansion of macro ‘SYSCALL_REGS_PREPARE’
  147 |         SYSCALL_REGS_PREPARE(syscall_regs, nr, arg1, arg2, arg3, arg4, arg5, arg6);

Fix: commit 33b244d141ce ("{aarch64,x86_64}/regs.h: Code style")
Signed-off-by: Rong Tao <rongtao@cestc.cn>